### ISSUE TITLE
The checkpoint of model trained on CLEVR-3D

### ISSUE THREAD

**Issue by Anqw** [stelzner/osrt#2]
Hi, thanks for reproducing this interesting work.
Could you please provide the checkpoint of model trained on CLEVR-3D?

**Comment by stelzner** [comment]
I just added a CLEVR-3D checkpoint to the readme. Hope this helps!

**Comment by takerum** [comment]
Thank you very much for providing the checkpoint! 
Let me ask another question: How long does it take to get to that checkpoint?  When I run the code in my environment (8xA100 GPUs), I found it would take ~10 days to complete the total iterations (4x10^6), which I think is relatively long. I suspect there is something wrong with my environment, and I just would like to know whether such a long time training is due to my environment, or just normal behavior.

**Comment by stelzner** [comment]
That sounds about right, actually. I've found the model to converge quite a bit sooner though, hence the checkpoint sits at about 1M iterations. That took about 5 days for me to train, but I don't quite remember how many GPUs I was using.
